# Site settings
title: Stop Bored Play Board
email: konsent2@gmail.com
description: "보드게임 일기장"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://konsent.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  konsent

# Build settings
markdown: kramdown
permalink: pretty
timezone: Asia/Seoul
future: true

# Analytics
analytics:
  provider:
    "google-gtag"
    # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id: "G-CSE0M4Q6E6"
    anonymize_ip: # true, false (default)


